FROM node:{{ node_version }}-alpine

WORKDIR /app

# Copy workspace files
COPY package.json ./
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN corepack enable && \
    corepack prepare pnpm@{{ pnpm_version }} --activate && \
    pnpm install --frozen-lockfile

CMD ["pnpm", "run", "start"] 